### ISSUE TITLE
PaloAlto: GlobalProtect dashboard has a search syntax error in tile

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/kits#163]
## What are the steps to reproduce this issue?

1. Load palo alto data
2. Load up kit
3. Load GlobalProtect dashboard

## What happens?

2nd row tile on the left has a syntax error on line 6

## What were you expecting to happen?

Not have syntax error

## Any logs, error output, etc?

...

## Any other comments?

...

## What versions of software are you using?

**Browser:** ...

**GUI Build Version:** ...

**Comment by david-fritz-gravwell** [comment]
offending line is:

```
eval $(Pre-tunnel Latency (ms)) = pre / 1000000; $(Post-tunnel Latency (ms)) = post / 1000000; 
```

You cannot have a close paren inside an EV literal `$()` because the close paren _is_ the closing character. Before you ask why -- it's no different than a raw quoted string in go -- there's NO way to have a closing backtick, even with an escape character, in a raw quoted string. Same here with close paren.
